'use strict';
// Defina os contatos reais para ativar os links externos.
const CONFIG = { whatsapp: '5574999504255', instagram: '', maps: '' };
const paths = {
 heart:'<path d="M12 21S2 15 2 8a5 5 0 0 1 10-2 5 5 0 0 1 10 2c0 7-10 13-10 13Z"/>',
 bowl:'<path d="M3 11h18l-2 9H5l-2-9Z"/><path d="M3 11c0-4 18-4 18 0M7 5l1-2m4 3V2m5 3-1-2"/>',
 spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7ZM3 3l2 2m14 14 2 2"/>',
 collar:'<path d="M3 9c0-6 18-6 18 0v7c0 6-18 6-18 0V9Z"/><path d="M3 9c0 6 18 6 18 0M8 13h8v6H8zM12 16h2"/>',
 ball:'<circle cx="12" cy="12" r="10"/><path d="M7 3c8 5 8 13 0 18M17 3c-8 5-8 13 0 18"/>',
 paw:'<ellipse cx="12" cy="16" rx="6" ry="5"/><ellipse cx="5" cy="9" rx="2" ry="3"/><ellipse cx="10" cy="5" rx="2" ry="3"/><ellipse cx="16" cy="5" rx="2" ry="3"/><ellipse cx="21" cy="10" rx="2" ry="3"/>',
 bag:'<path d="M4 7h16l1 14H3L4 7Z"/><path d="M8 8V5a4 4 0 0 1 8 0v3"/>'
};
const icon = name => `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">${paths[name]}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el => el.innerHTML=icon(el.dataset.icon));
const drawings = {
 food:'<path d="M58 24h84l15 147H42L58 24Z" fill="#d87735"/><path d="M61 24h78l-3 12H64Z" fill="#a84d22"/><rect x="55" y="65" width="90" height="61" rx="8" fill="#f7e7d0"/><text x="100" y="91" text-anchor="middle" font-family="Arial" font-size="22" font-weight="bold" fill="#6b2720">MIAU</text><text x="100" y="111" text-anchor="middle" font-family="Arial" font-size="10" fill="#6b2720">PREMIUM</text><path d="M67 147h66" stroke="#f7e7d0" stroke-width="4"/>',
 treat:'<path d="M59 30h82l8 140H51l8-140Z" fill="#2ad199"/><path d="M58 38h84" stroke="#168e65" stroke-width="8"/><rect x="64" y="65" width="72" height="65" rx="8" fill="#f7e7d0"/><path d="M83 87c-8-13-18 2-8 8l42 13c6 11 20 0 9-8 12-10 0-19-8-9L83 87Z" fill="#d87735"/><text x="100" y="151" text-anchor="middle" font-family="Arial" font-size="13" fill="#6b2720">MIAU</text>',
 ball:'<circle cx="100" cy="101" r="62" fill="#2ad199"/><path d="M68 49c65 30 65 83 0 105M132 49c-65 30-65 83 0 105" fill="none" stroke="#f7e7d0" stroke-width="18"/><path d="M48 96h104" stroke="#d87735" stroke-width="19"/>',
 collar:'<ellipse cx="100" cy="107" rx="75" ry="30" fill="#6b2720"/><path d="M25 105v25c5 45 145 45 150 0v-25c-9 36-141 36-150 0Z" fill="#d87735"/><rect x="74" y="119" width="44" height="33" rx="4" fill="none" stroke="#f7e7d0" stroke-width="6"/><path d="M96 122v27" stroke="#f7e7d0" stroke-width="4"/><circle cx="146" cy="142" r="3" fill="#6b2720"/>',
 bed:'<ellipse cx="100" cy="129" rx="83" ry="36" fill="#6b2720"/><ellipse cx="100" cy="113" rx="83" ry="40" fill="#d87735"/><ellipse cx="100" cy="108" rx="58" ry="24" fill="#f7e7d0"/><path d="M34 115c10 48 122 48 132 0" fill="none" stroke="#b65b27" stroke-width="8"/>',
 shampoo:'<rect x="69" y="28" width="62" height="27" rx="7" fill="#6b2720"/><rect x="59" y="51" width="82" height="124" rx="19" fill="#2ad199"/><rect x="67" y="83" width="66" height="63" rx="7" fill="#f7e7d0"/><text x="100" y="106" text-anchor="middle" font-family="Arial" font-size="16" font-weight="bold" fill="#6b2720">MIAU</text><path d="M100 116c-25 24 25 24 0 0Z" fill="#d87735"/><text x="100" y="161" text-anchor="middle" font-family="Arial" font-size="8" fill="#6b2720">CUIDADO & CARINHO</text>'
};
const products=[
 {name:'Ração premium',category:'alimentacao',label:'Alimentação',text:'Sabor e cuidado em cada refeição.',art:'food',detail:'Uma opção ilustrativa para compor uma alimentação completa. A escolha da ração deve considerar a espécie, a idade e as necessidades individuais do seu pet.'},
 {name:'Petiscos especiais',category:'alimentacao',label:'Alimentação',text:'Um carinho entre uma brincadeira e outra.',art:'treat',detail:'Petiscos para transformar pequenos momentos em recompensas. Consulte a composição e as porções indicadas na embalagem antes de oferecer ao seu pet.'},
 {name:'Bola de brincar',category:'brinquedos',label:'Brinquedos',text:'Diversão para gastar energia junto.',art:'ball',detail:'Brinquedo ilustrativo para momentos de interação. Escolha o tamanho adequado ao seu pet e acompanhe as brincadeiras.'},
 {name:'Coleira com estilo',category:'acessorios',label:'Acessórios',text:'Personalidade para cada passeio.',art:'collar',detail:'Uma coleira para compor passeios cheios de personalidade. Confira as medidas do pescoço e mantenha um ajuste confortável.'},
 {name:'Caminha aconchego',category:'acessorios',label:'Acessórios',text:'Um cantinho para sonhar e descansar.',art:'bed',detail:'Conforto para as pausas do dia. Escolha uma cama com espaço para seu pet se esticar e materiais adequados à rotina de limpeza.'},
 {name:'Shampoo para pets',category:'higiene',label:'Higiene',text:'Carinho que faz parte da rotina.',art:'shampoo',detail:'Produto ilustrativo de higiene. Use apenas produtos apropriados para a espécie e siga as orientações do fabricante. Em caso de problemas de pele, procure orientação veterinária.'}
];
const grid=document.getElementById('product-grid');
products.forEach((p,i)=>{const card=document.createElement('article');card.className='product';card.dataset.category=p.category;card.innerHTML=`<div class="product-art"><img src="images/produto-base.webp" alt="" width="600" height="500" loading="lazy"><svg aria-hidden="true" viewBox="0 0 200 200">${drawings[p.art]}</svg><span class="tag">Seleção MIAU</span></div><div class="product-body"><p class="eyebrow">${p.label}</p><h3>${p.name}</h3><p>${p.text}</p><button class="text-link" data-product="${i}" aria-label="Ver produto: ${p.name}">Ver produto <span aria-hidden="true">↗</span></button></div>`;grid.append(card);});
const dialog=document.getElementById('detail-dialog');const content=document.getElementById('dialog-content');let lastFocus;
function show(html){if(!dialog.open)lastFocus=document.activeElement;content.innerHTML=html;if(!dialog.open)dialog.showModal();document.body.style.overflow='hidden';}
function close(){dialog.close();}
dialog.querySelector('.dialog-close').addEventListener('click',close);
dialog.addEventListener('close',()=>{document.body.style.overflow='';lastFocus?.focus();});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
function contact(channel){let url='';if(channel==='WhatsApp'&&/^\d{10,15}$/.test(CONFIG.whatsapp))url=`https://wa.me/${CONFIG.whatsapp}`;if(channel==='Visita'&&CONFIG.maps)url=CONFIG.maps;if(channel==='Instagram'&&CONFIG.instagram)url=`https://www.instagram.com/${encodeURIComponent(CONFIG.instagram)}/`;if(url){window.open(url,'_blank','noopener,noreferrer');return;}show(`<p class="eyebrow">Projeto de portfólio</p><h2 id="dialog-title">${channel==='Visita'?'Um lugar de carinho.':channel==='Instagram'?'Nosso carinho nas redes.':'Vamos conversar?'}</h2><p>A MIAU é uma marca fictícia criada para apresentar um projeto de branding e landing page. ${channel==='Visita'?'O endereço e os horários apresentados são ilustrativos.':channel==='Instagram'?'As artes do feed são demonstrativas; o perfil oficial ainda não foi definido.':'O número de atendimento pelo WhatsApp ainda não foi definido.'}</p><div class="dialog-note">Quando os dados oficiais forem definidos, este botão poderá abrir o contato diretamente.</div>`);}
document.addEventListener('click',e=>{const p=e.target.closest('[data-product]');if(p){const product=products[Number(p.dataset.product)];show(`<p class="eyebrow">${product.label} · Catálogo ilustrativo</p><h2 id="dialog-title">${product.name}</h2><p>${product.detail}</p><div class="dialog-note">Imagem conceitual. Marcas, tamanhos, disponibilidade e valores serão definidos no catálogo final.</div><p><button class="button" data-contact="WhatsApp">Consultar pelo WhatsApp ↗</button></p>`);}const c=e.target.closest('[data-contact]');if(c){contact(c.dataset.contact);}});
function filter(value){document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===value;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});let n=0;document.querySelectorAll('.product').forEach(p=>{p.hidden=value!=='todos'&&p.dataset.category!==value;if(!p.hidden)n++;});document.getElementById('filter-status').textContent=`${n} produtos exibidos.`;window.ScrollTrigger?.refresh();}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));
document.querySelectorAll('[data-category]').forEach(a=>a.addEventListener('click',()=>filter(a.dataset.category)));
const serviceText={'Banho e tosa':'Um momento dedicado à limpeza e ao conforto do seu pet. O atendimento, os tipos de tosa e os valores serão definidos na versão comercial.','Higiene':'Cuidados para uma rotina mais confortável. Os procedimentos disponíveis serão confirmados no catálogo de serviços.','Orientação na escolha de produtos':'Uma conversa para ajudar a escolher alimentos, acessórios e brinquedos adequados à fase e à rotina do seu pet.','Entrega':'Praticidade para receber seus produtos. A área de cobertura, os horários e a taxa serão definidos antes da operação da loja.'};
document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>show(`<p class="eyebrow">Cuidado MIAU · Serviço ilustrativo</p><h2 id="dialog-title">${b.dataset.service}</h2><p>${serviceText[b.dataset.service]}</p><button class="button" data-contact="WhatsApp">Fale com a MIAU ↗</button>`)));
document.getElementById('instagram-cta').addEventListener('click',()=>contact('Instagram'));
const toggle=document.querySelector('.menu-toggle');const nav=document.getElementById('navigation');function closeMenu(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir menu');toggle.textContent='☰';}toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');toggle.textContent=open?'×':'☰';});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});document.addEventListener('click',e=>{if(!e.target.closest('.nav'))closeMenu();});
document.getElementById('year').textContent=new Date().getFullYear();window.addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',window.scrollY>20),{passive:true});
if(window.gsap&&window.ScrollTrigger){gsap.registerPlugin(ScrollTrigger);gsap.matchMedia().add('(prefers-reduced-motion: no-preference)',()=>{const tl=gsap.timeline({defaults:{duration:.8,ease:'power2.out'}});tl.from('.hero h1 span',{y:35,opacity:0,stagger:.1}).from('.hero .lead',{y:15,opacity:0},'-.5').from('.hero .actions>*',{y:12,opacity:0,stagger:.1},'-.5').from('.hero-art',{x:25,opacity:0,scale:.97},'-.8');gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:22,opacity:0,duration:.65,scrollTrigger:{trigger:el,start:'top 92%',once:true}}));const bt=gsap.timeline({scrollTrigger:{trigger:'.emotional',start:'top 82%',once:true}});bt.from('.emotional h2>span',{y:22,opacity:0,stagger:.17,duration:.7}).from('.emotional .button',{y:10,opacity:0,duration:.5},'-.2').from('.banner-heart',{rotation:3,opacity:0,duration:.5},'-.4');gsap.from('#instagram .social-photo',{y:18,scale:.98,opacity:0,duration:.75,ease:'power2.out',scrollTrigger:{trigger:'#instagram',start:'top 85%',once:true}});gsap.from('#instagram .social-copy',{y:12,opacity:0,duration:.65,delay:.12,ease:'power2.out',scrollTrigger:{trigger:'#instagram',start:'top 85%',once:true}});return()=>{};});}
